baseURL = '/'
languageCode = 'en-us'
title = 'Eino Rauhala'
theme = ['hugo-video','ehr']
relativeURLs = "true"

[privacy]
  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

menu = 'main'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = -110
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = -100
[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = -90